### ISSUE TITLE
Make `grantRTokenAllowance` work for multiple calls to a token like USDT

### ISSUE THREAD

**Issue by tbrent** [reserve-protocol/protocol#383]
USDT has a weird requirement that either the allowance being set must be 0 or that the already-set allowance is 0. 

We use `.safeIncreaseAllowance`, which won't work with this logic. We probably need to use `safeApprove`, and make multiple calls?

This also probably impacts allowances elsewhere. Should scan through rest of code and make sure everywhere we grant allowances we use a robust approach.

**Comment by tbrent** [comment]
Julian says we'll need to touch: BackingManager, RevenueTrader, Trading.sol, GnosisTrade

**Comment by julianmrodri** [comment]
Those are the only contracts where we currently use `safeIncreaseAllowance`. We should also adjust it for P0 for compatiblity. We still need to use `safeApprove` because of handling the USDT interface (which is different than the other ERC20s). So two calls to `safeApprove` (0 and the new amount)  should fix this.
