### ISSUE TITLE
[Discussion] Issues with Revenue Hiding Guidance 

### ISSUE THREAD

**Issue by larrythecucumber321** [reserve-protocol/protocol#503]
## Summary

The [Guide](https://github.com/reserve-protocol/protocol/blob/master/docs/collateral.md#revenue-hiding) for writing collateral plugins suggests that Revenue Hiding can be performed by discounting the `refPerTok()` function by anticipated fluctuations. However, the example below reveals that this could lead to unintended/undesirable effects on resultant rToken prices (rToken prices > 1 to start). Links are included to locations of relevant code/calculations.

## Example Revenue Hiding scenario
1. User wishes to mint 10,000 rTokens in a basket comprising 100% of a single collateral token (CT)
2. User must deposit $10,000 USD worth of CTs
3. Assuming a `price()/strictPrice()` of $1/CT, user is required to deposit 10k CTs
4. Price of CT collateral can fluctuate up to 2%, so `refPerTok()` is marked down by 2% from its true price (as per the guidance)
5. This will result in the minted rTokens to have a price of $1.0204 at inception 

### rToken issuance
- [`issue()`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/RToken.sol#L140) is first invoked with `amount = 10000` (assume everything is padded to 18 decimals)
- [`basketHandler.quote()`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/RToken.sol#L156) is invoked to determine # of tokens to transfer from user
- [`quote()`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/BasketHandler.sol#L343) invokes [`quantity()`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/BasketHandler.sol#L278), which returns the quotient of the token's reference amount in the basket and `refPerTok()`
- the `quantity` is multiplied by # of rTokens requested to arrive at the final quote
- Result:
  - `quantity(CT)` returns 1/0.98, or 1.0204
  - `quote(10000)` returns 10204 CT for fulfilling the request of 10000 rTokens

### Subsequent rToken price calculation
- [Price](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/BasketHandler.sol#L295) is the aggregate product of collateral prices and reference quantities of those collateral assets
- A collateral token's [`price()/strictPrice()`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/BasketHandler.sol#L302) is first calculated
- This price is [multiplied by the `quantity`](https://github.com/sraver/reserve-protocol/blob/master/contracts/p0/BasketHandler.sol#L320)
- `quantity` is calculated as `basket.refAmts[erc20].div(refPerTok, CEIL)`
- Result: 
  - `price()/strictPrice() = 1`
  - `quantity = 1/0.98 = 1.0204`
  - Finally, the `price` of our rToken is calculated as `1 * 1.0204 = 1.0204`. **This is bad because we expect an rToken to be priced at $1 at inception.**

## Discussion
- This assumes that rTokens should start with a price of $1 and only appreciates with its underlying collateral
- The underlying system does not tolerate manipulation of `refPerTok`
- Consider whether the right solution is limiting revenue hiding only to the default check in a collateral adapter's `refresh()` (I don't have the full context to know whether this solution might violate other protocol invariants)
```solidity
        // Check for hard default
        uint192 referencePrice = refPerTok();
        if (referencePrice < prevReferencePrice.mul(minAcceptableFloor).div(floorDenom)) {
            markStatus(CollateralStatus.DISABLED);
        }
```

**Comment by tbrent** [comment]
This is the expected behavior. Limiting the revenue hiding only to the default check breaks the protocol's underlying economics, which require `refPerTok()` never decreases. If it does decrease, then revenue may have already been handed out, and this would cause `BasketHandler.fullyCollateralized()` to become false, triggering recollateralization auctions. This would be okay if the recollateralization auctions were paid for by RToken holders + stakers in the same proportion as the revenue splits, but the protocol bills stakers for _all_ deficits. Even if we were to sophisticate this logic, the presence of additional optional revenue destinations would make this insufficient. Repeated rises and falls of the `refPerTok()` would leak out value to these revenue destinations over time, since they benefit from the increases without being asked to pay for the decreases. 

Also it's not actually an invariant that an RToken should start being worth $1. That's why `targetPerRef()` is free and not assumed to be 1, not to mention the prime basket can set with target amounts that do not sum to 1. 

You're right though that this does produce some undesired consequences. The RToken's price is free to oscillate by the revenue hiding percentage discounted by the fraction of the basket it makes up. So it's a bit of a different guarantee for RToken holders. Still, without changing the protocol much more fundamentally I think this is the best solution we have available for handling collateral tokens that depreciate sometimes.

**Comment by larrythecucumber321** [comment]
Thank you for the explanation @tbrent - closing because what I've raised is clearly not an issue 🙂
